### PR TITLE
Actual/Target/Dashboard from db

### LINKED ISSUE #61: Actual/Target attribute disaggregation for datasets
- [x] \[metadata\] Create categoy combo  with dataDimension = ATTRIBUTE (category = actual/target)
- [x] \[app\] Save datasets with this new catCombo.
- [x] \[data-entry\] Modify logic to select option in dropdown => @laurapareja
- [x] Fix errors in goback button (Actual Values page)
- [x] Read available periods for dataset  and display in the drop down. Select the first available period.  Note periods can be in different year. For reference, see https://github.com/EyeSeeTea/vaccination-app/blob/master/src/components/data-entry/DataEntry.jsx#L98 and https://github.com/EyeSeeTea/vaccination-app/blob/master/src/models/datasets.js#L99

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

* **Issue:** Closes #61, #71

* **project-monitoring-metadata**: Requires https://bitbucket.org/eyeseetea/project-monitoring-metadata/pull-requests/2 (already deployed to dev2)

### :memo: Implementation

- Set actual/target category combo for created datasets.
- Actual/target category filter (using a prop in DataEntry)
- Fix error in `goBack button` (Actual values/Target values/Dashboard components)
- Set expiryDays by data set type
- Populate month by dataset dataInputPeriods and dataSet type.

### :art: Screenshots
Example of Data Entry in Actual Values & Target Values
image
image
Example of how filters are working behind
image
image

### CODE REVIEW

**Comment by tokland** [comment]
That's the "bad odate/cdate" issue I saw the other day. This moring it happened gain in my server and I took another look into it. I saw that the bad date comes from straight from the server, not a JS parsing issue. Check odate/cdate for the failing orgUnit and compare with the others:

http://dev2.eyeseetea.com:8081/dhis-web-commons-ajax-json/getOrganisationUnitTree.action

I checked values in DB, they were ok. I restarted the server and then the response was ok, that was really worrying. I'll have to look more into it, since it's happening also in dev2. It looks like a bug in dhis2-core but I'll have to debug it a llttle bit to be sure.

> Btw, did you finally implement the refresh of the org unit cache?

Not yet, sorry, I'll take a note for tomorrow.

**Comment by adrianq** [comment]
I have never seen this error in a regular data-entry though. I don't doubt it is coming from the backend but I guess it should be a combination of the iframe + the backend bug.

No worries about the cache thing. Just push in this PR when ready

**Comment by tokland** [comment]
> I have never seen this error in a regular data-entry though. I don't doubt it is coming from the backend but I guess it should be a combination of the iframe + the backend bug.

I re-saved the offending orgUnit and now the response is correct (YYYY-MM-DD). I'll check it out, I suspect it does not like something in the POST when saving, not a bug, but something with the iso format.

> No worries about the cache thing. Just push in this PR when ready

Ok!

**Comment by tokland** [comment]
The error appears also in the normal data entry. Tested with project Test1b, the third I had to create until the problem cdate/odate resurfaced. It's quite random, exact same POST worked two times before that.

**Comment by adrianq** [comment]
Buff, sounds a bit like the attribute bug you detected in 2.31. Didn't know what was the actual cause in the backend. Guess it only happens with the metadata endpoint

**Comment by tokland** [comment]
Just to be sure, the values were only not saved when you saw the "position 0" error on console, right? that would be "normal". So it failed on Test integration2 but worked on Test integration (where cdate/odate were ok)

**Comment by adrianq** [comment]
It actually never worked for any of them. I could see the error happening for the two of them. Not sure if the values were actually stored though. As I said, the background turns green but when refreshing the page or changing month they disappear. Never checked with the API

**Comment by adrianq** [comment]
... and yes, the values never show up when we have that js error

**Comment by tokland** [comment]
Workaround: https://github.com/EyeSeeTea/project-monitoring-app/pull/75/commits/2ae53f64ab3b7926d9c0c2ebe6d25fdb72ac43d7#diff-a918021dd0abc3079676edba1826160dR120

Ready for review

**Pull request merged**
