### PR TITLE
Sync filters with url

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

* **Issue:** Closes https://app.clickup.com/t/d8x88z

### :memo: Implementation

- Side work: Add infrastructure for proxied requests (circumvent cross-domain iframe)
- Side work: add pre-push hook to check uncommitted.
- Notes on the URL sync:
  - `fromParams`/`toParams` functions to convert/parse arbitrary objects to pretty query strings.
  - Query strings are validated.
  - URL sync implemented for both project and countries list.
  - URL sync works also on the first load.
  - Defaults query string values are removed from the URL so we keep it as clean as possible.
  - Back buttons work as the standard browser back button. However, if the page URL load came from the outside, go to the default back page (using react-router-last-location for that).
  - Most of this work can be reused when we implement our own react router infrastructure. Some notes for that moment: use context to have a single source of truth; allow different components to sync to the query strings in isolation. Use a schema to automatically map/validate filter<->query strings.
image

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland I think you need to refactor this PR. In this PR, you are changing ObjectsList.tsx and objects-list-hook.ts but these two classes were "moved" to d2-ui-comp in this PR https://github.com/EyeSeeTea/project-monitoring-app/pull/368 I have merging and solving conflicts for the previous PRs but if I am not wrong this requires some major changes (new PR to d2-ui-comp, merge with development, etc). Please take care of this whenever you can and give me a shout!

**Comment by tokland** [comment]
Let's discuss this on Monday. My take: `ObjectsList`/`useObjectsList  in d2-ui-components are useful in the general case, it has been our stable use on many apps, but I would not try to move these changes to d2-ui-components just yet. The URL-syncing is part of a major effort concerning routing, which requires some team discussion and time (not less than 15-20h). So I'd say to use the custom app ObjectsList here and keep it as a reference for future developments.

**Comment by adrianq** [comment]
OK, I understand the issue here. It was just that we had a previous PR that substitute the custom object list with the d2-ui-component object list (and remove those two files). Are you saying to somehow revert that [PR](https://github.com/EyeSeeTea/project-monitoring-app/pull/368)?

**Comment by tokland** [comment]
Yes, reverting it will be the simplest. Sorry, I did not remember we had that PR.

**Comment by adrianq** [comment]
No worries :) Just go ahead and revert the PR in this branch and merge it with development please. Thanks!

**Comment by tokland** [comment]
@est/d2-ui-components addition not reverted, we want the new package, just let's use custom app components and hook for the table. Ready for review.

**Pull request merged**
